### ISSUE TITLE
Cannot start new game

### ISSUE THREAD

**Issue by tms792** [rsandzimier/battleline#3]
Able to enter as a new player, but cannot start a new game.

**Comment by rsandzimier** [comment]
Hello. This is a known issue. On November 28, 2022, Heroku got rid of their free tier. I was using the free tier for the Battleline backend, so that broke the Battleline backend.

It’s on my to do list to fix it by migrating to [FreeBoardGames.org](https://github.com/freeboardgames/FreeBoardGames.org). I think it will get more traffic there as well. I am hoping to fix it by June 2023, but it depends on when I can get around to it.

If you are trying to play against someone in the same room as you, there is a way to play it locally from 1 computer. If that interests you, I can add some documentation for how to run it locally. 

If there is enough interest, I can upgrade my Heroku account to a paid account as a quick fix until I am able to move away from Heroku.

**Comment by tms792** [comment]
Hi there,

Ah that makes total sense. My long-distance boyfriend and I absolutely
adore the card game and had been using your program to play during the
weeks we are apart. I know this is probably a long shot, but I would be
happy to cover the cost of the Heroku monthly fee for the next ~six months
as you have time to migrate it over to FreeBoardGames.org
<http://freeboardgames.org/>. If not, I totally understand!

In the interim, if you are easily able to share the documentation on how to
play it locally from one computer, that would be awesome.

Thank you so much,
Tasha

**Comment by rsandzimier** [comment]
Hi! It’s so awesome to hear that you’ve been somewhat regularly enjoying playing! Sorry for the unannounced downtime. I let it lapse because I didn’t know anyone was actually playing. 

My wife and I dated long distance before we got married, so I know how hard it can be and how little things like this can really make it easier! I’ll upgrade the Heroku account and try to get the game back up and running either tonight or tomorrow. Thank you for offering to cover the cost, but I’ve got it. It will be extra motivation to follow through with my plans to migrate the game :)

**Comment by rsandzimier** [comment]
Hello. It should be up and running now on the site. Let me know if you have any other issues.

**Comment by tms792** [comment]
Thank you so much! Your kindness and generosity are so appreciated. Thank
you a million times over!

**Comment by tms792** [comment]
Thank you again! This has brought so much joy to our relationship!
